### ISSUE TITLE
adding projects 

### ISSUE THREAD

**Issue by manasbhandari** [Arunb-lab1/Hacktoberfest2022#105]
heyy @Arunb-lab1 , 
please allow me to add some of the interesting small project into your repository 

also please kindly add hactoberfest label to it

**Comment by Arunb-lab1** [comment]
Sure Manas

**Comment by manasbhandari** [comment]
hello @Arunb-lab1 
I have created a pull request for the same. please review #138

**Comment by pjyoti121** [comment]
Please assign me this issue

**Comment by laveshverma007** [comment]
I would be happy to contribute please assign to me under hacktoberfest

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by SJ-Kumar** [comment]
I would like to add an interesting Hangman game project i have done using python. Please assign it to me.

**Comment by JAHANVIGUPTA1775** [comment]
@Arunb-lab1 pls assign me this.

**Comment by laveshverma007** [comment]
> @Arunb-lab1 pls assign me this.

This repo is excluded in hactoberfest🥲

**Comment by manasbhandari** [comment]
your repo is been exlcluded from the hacktoberfest.
