### ISSUE TITLE
Blog Website

### ISSUE THREAD

**Issue by tarunbisht-24** [Arunb-lab1/Hacktoberfest2022#134]
I want to add a blog website which is basically built on frontend and backend like HTML, CSS, JS and Nodejs. Please assign me this issue under Hacktoberfest 2022 tag.

**Comment by Arunb-lab1** [comment]
Done

**Comment by tarunbisht-24** [comment]
@Arunb-lab1 thanks for that but can you pls add the hacktoberfest tags?

**Comment by Arunb-lab1** [comment]
sorry for my mistake :-(

**Comment by tarunbisht-24** [comment]
thanks ;)
