### ISSUE TITLE
Create a new Webpage

### ISSUE THREAD

**Issue by niranjan-kurhade** [Arunb-lab1/Hacktoberfest2022#2]
Hey, I am also a beginner in Open-Source! I Want to Contribute something. So should I Add something? Like a Basic Website using Html, Css?

**Comment by Arunb-lab1** [comment]
You can contribute on whatever you like brother you can fork this repo and add whatever you like to add.

**Comment by niranjan-kurhade** [comment]
Hey please Review and Merge my Pull Request.
Will Add some more stuff!

**Comment by niranjan-kurhade** [comment]
> You can contribute on whatever you like brother you can fork this repo and add whatever you like to add.


Hey please Review and Merge my Pull Request.
Will Add some more stuff!

**Comment by Arunb-lab1** [comment]
Done..... keep contributing..

**Comment by niranjan-kurhade** [comment]
> Done..... keep contributing..

Hey not able to push more code Says"remote: Permission to Arunb-lab1/Hacktoberfest2022.git denied to niranjan-kurhade."

**Comment by niranjan-kurhade** [comment]
> Done..... keep contributing..

hey not able to push more code it says"remote Permission to fatal unable to access The requested URL returned error 403"

**Comment by Arunb-lab1** [comment]
let me check right now

**Comment by Arunb-lab1** [comment]
bro it's working fine from my side can you check again?
