### ISSUE TITLE
Top contributors section

### ISSUE THREAD

**Issue by Arunb-lab1** [Arunb-lab1/Hacktoberfest2022#62]
Hi Someone contribute for making attractive top contributors section?

**Comment by AmitBarman99** [comment]
Ok I want to create the CONTRIBUTORS.md file for this repo. Can you assign me for this ?

I also want to arrange the file system here . Can I do this?

**Comment by Arunb-lab1** [comment]
> Ok I want to create the CONTRIBUTORS.md file for this repo. Can you assign me for this ?
> 
> I also want to arrange the file system here . Can I do this?

Yes you can sir! go fo it..

**Comment by AmitBarman99** [comment]
@Arunb-lab1 completed
You can find it here #83

**Comment by Arunb-lab1** [comment]
> @Arunb-lab1 completed You can find it here #83

Hi sir, Someone messed up top contributes section can you fix that  ??

**Comment by AmitBarman99** [comment]
Ok , i will fix it. 
Working on it

**Comment by AmitBarman99** [comment]
#147 
Completed.
